services:
  studiowebux-landing:
    image: nginx:1.29.2-perl
    container_name: studiowebux-landing
    restart: unless-stopped
    volumes:
      - ./src/:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=studiowebux.com,www.studiowebux.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=studiowebux.com,www.studiowebux.com
    networks:
      - proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "25M"

networks:
  proxy:
    name: proxy
    external: true
